spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

# 修改项目默认端口8080
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
